security:
    encoders:
        Symfony\Component\Security\Core\User\User: md5

    providers:
      in_memory:
        entity: { class: Acme\Bundle\Entity\Account, property: email }

    role_hierarchy:
        ROLE_UNKOWN:              ROLE_USER
        ROLE_EMPLOYER_LIMITED:    ROLE_USER
        ROLE_EMPLOYER_UNLIMITED:  ROLE_USER
        ROLE_SEEKER:              ROLE_USER
        #ROLE_ADMIN: [ROLE_SEEKER, ROLE_EMPLOYER, ROLE_USER, ROLE_ALLOWED_TO_SWITCH]

    acl:
        connection: default

    firewalls:
        profiler:
            pattern:  ^/_profiler
            security: false

        wdt:
            pattern:  ^/_wdt
            security: false
            
        configurator:
            pattern: ^/_configurator
            security: false
            
        login:
            pattern:  ^/login$
            security: false
        remember_me:
            key: "%secret%"
            lifetime: 3600
            path: /
            domain: ~
			
        secured_admin_area:
            pattern:    ^/admin.*
            access_denied_url: /error403
            form_login:
                check_path: /login_check
                login_path: /login
            logout:
                path:   /logout
                target: /
            anonymous: ~        

        secured_applay_area:
            pattern:    ^/job/apply.*
            access_denied_url: /error403
            form_login:
                check_path: /login_check
                login_path: /login
                email_parameter: _email
                password_parameter: _password
            logout:
                path:   /logout
                target: /
            anonymous: ~
        secured_profile_area:
          #for seeker
           pattern:    ^/profile.* 
           access_denied_url: /
           form_login:
               check_path: /login_check
               login_path: /login
               email_parameter: _email
               password_parameter: _password
            logout:
               path:   /logout
               target: /
            anonymous: ~
           #for Employer			
        secured_dashboard_area:
            pattern:    ^/dashboard.*
            access_denied_url: /
            form_login:
                check_path: /login_check
                login_path: /login
                email_parameter: _email
                password_parameter: _password
            logout:
                path:   /logout
                target: /
            anonymous: ~
    access_control:
      - { path: ^/admin.*, roles: [ROLE_ADMIN] }
      - { path: ^/profile.*, roles: [ROLE_SEEKER] }
      - { path: ^/dashboard.*, roles: [ROLE_EMPLOYER_LIMITED],[ROLE_EMPLOYER_UNLIMITED] }
      - { path: ^/job/apply.*, roles: ['ROLE_SEEKER','ROLE_ADMIN] }
     #- { path: ^/seeker.*, roles: [ROLE_SEEKER] }