KareerakFrontendBundle_homepage:
    pattern:  /
    defaults: { _controller: KareerakFrontendBundle:Default:index }

KareerakFrontendBundle_login:
    pattern: /login
    defaults: { _controller: KareerakFrontendBundle:Security:login }
