parameters:
#    kareerak_frontend.example.class: Kareerak\FrontendBundle\Example

services:
#    kareerak_frontend.example:
#        class: %kareerak_frontend.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
