<?php

namespace Kareerak\FrontendBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * Career_LevelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Career_LevelRepository extends EntityRepository
{
}