<?php

namespace Kareerak\FrontendBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * Email_AddressRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Email_AddressRepository extends EntityRepository
{
}