<?php

namespace Kareerak\FrontendBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * Industry_SkillRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Industry_SkillRepository extends EntityRepository
{
}