<?php

namespace Kareerak\FrontendBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * Job_SkillRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Job_SkillRepository extends EntityRepository
{
}