<?php

namespace Kareerak\FrontendBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * Seeker_CertificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Seeker_CertificationRepository extends EntityRepository
{
}